# Generated by Django 2.1.5 on 2019-06-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tapId', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.CharField(blank=True, max_length=250, null=True)),
                ('currency', models.CharField(blank=True, max_length=250, null=True)),
                ('transactionId', models.CharField(blank=True, max_length=250, null=True)),
                ('trackId', models.CharField(blank=True, max_length=250, null=True)),
                ('paymentId', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='main.Renter')),
            ],
        ),
    ]
